package org.rsc.liferay.contact.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.rsc.liferay.contact.model.Contact;
import org.rsc.liferay.contact.model.ContactModel;
import org.rsc.liferay.contact.model.ContactSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Contact service. Represents a row in the &quot;rsc_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.rsc.liferay.contact.model.ContactModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactImpl
 * @see org.rsc.liferay.contact.model.Contact
 * @see org.rsc.liferay.contact.model.ContactModel
 * @generated
 */
@JSON(strict = true)
public class ContactModelImpl extends BaseModelImpl<Contact>
    implements ContactModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contact model instance should use the {@link org.rsc.liferay.contact.model.Contact} interface instead.
     */
    public static final String TABLE_NAME = "rsc_Contact";
    public static final Object[][] TABLE_COLUMNS = {
            { "personId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "lastName", Types.VARCHAR },
            { "firstName", Types.VARCHAR },
            { "mail", Types.VARCHAR },
            { "phone", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table rsc_Contact (personId LONG not null primary key,companyId LONG,lastName VARCHAR(75) null,firstName VARCHAR(75) null,mail VARCHAR(75) null,phone VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table rsc_Contact";
    public static final String ORDER_BY_JPQL = " ORDER BY contact.lastName ASC, contact.firstName ASC";
    public static final String ORDER_BY_SQL = " ORDER BY rsc_Contact.lastName ASC, rsc_Contact.firstName ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.org.rsc.liferay.contact.model.Contact"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.org.rsc.liferay.contact.model.Contact"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.org.rsc.liferay.contact.model.Contact"));
    private static ClassLoader _classLoader = Contact.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Contact.class
        };
    private long _personId;
    private long _companyId;
    private String _lastName;
    private String _firstName;
    private String _mail;
    private String _phone;
    private Contact _escapedModel;

    public ContactModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Contact toModel(ContactSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Contact model = new ContactImpl();

        model.setPersonId(soapModel.getPersonId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setLastName(soapModel.getLastName());
        model.setFirstName(soapModel.getFirstName());
        model.setMail(soapModel.getMail());
        model.setPhone(soapModel.getPhone());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Contact> toModels(ContactSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Contact> models = new ArrayList<Contact>(soapModels.length);

        for (ContactSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _personId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPersonId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _personId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Contact.class;
    }

    @Override
    public String getModelClassName() {
        return Contact.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("personId", getPersonId());
        attributes.put("companyId", getCompanyId());
        attributes.put("lastName", getLastName());
        attributes.put("firstName", getFirstName());
        attributes.put("mail", getMail());
        attributes.put("phone", getPhone());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long personId = (Long) attributes.get("personId");

        if (personId != null) {
            setPersonId(personId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        String lastName = (String) attributes.get("lastName");

        if (lastName != null) {
            setLastName(lastName);
        }

        String firstName = (String) attributes.get("firstName");

        if (firstName != null) {
            setFirstName(firstName);
        }

        String mail = (String) attributes.get("mail");

        if (mail != null) {
            setMail(mail);
        }

        String phone = (String) attributes.get("phone");

        if (phone != null) {
            setPhone(phone);
        }
    }

    @JSON
    @Override
    public long getPersonId() {
        return _personId;
    }

    @Override
    public void setPersonId(long personId) {
        _personId = personId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public String getLastName() {
        if (_lastName == null) {
            return StringPool.BLANK;
        } else {
            return _lastName;
        }
    }

    @Override
    public void setLastName(String lastName) {
        _lastName = lastName;
    }

    @JSON
    @Override
    public String getFirstName() {
        if (_firstName == null) {
            return StringPool.BLANK;
        } else {
            return _firstName;
        }
    }

    @Override
    public void setFirstName(String firstName) {
        _firstName = firstName;
    }

    @JSON
    @Override
    public String getMail() {
        if (_mail == null) {
            return StringPool.BLANK;
        } else {
            return _mail;
        }
    }

    @Override
    public void setMail(String mail) {
        _mail = mail;
    }

    @JSON
    @Override
    public String getPhone() {
        if (_phone == null) {
            return StringPool.BLANK;
        } else {
            return _phone;
        }
    }

    @Override
    public void setPhone(String phone) {
        _phone = phone;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Contact.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Contact toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Contact) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ContactImpl contactImpl = new ContactImpl();

        contactImpl.setPersonId(getPersonId());
        contactImpl.setCompanyId(getCompanyId());
        contactImpl.setLastName(getLastName());
        contactImpl.setFirstName(getFirstName());
        contactImpl.setMail(getMail());
        contactImpl.setPhone(getPhone());

        contactImpl.resetOriginalValues();

        return contactImpl;
    }

    @Override
    public int compareTo(Contact contact) {
        int value = 0;

        value = getLastName().compareToIgnoreCase(contact.getLastName());

        if (value != 0) {
            return value;
        }

        value = getFirstName().compareToIgnoreCase(contact.getFirstName());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Contact)) {
            return false;
        }

        Contact contact = (Contact) obj;

        long primaryKey = contact.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Contact> toCacheModel() {
        ContactCacheModel contactCacheModel = new ContactCacheModel();

        contactCacheModel.personId = getPersonId();

        contactCacheModel.companyId = getCompanyId();

        contactCacheModel.lastName = getLastName();

        String lastName = contactCacheModel.lastName;

        if ((lastName != null) && (lastName.length() == 0)) {
            contactCacheModel.lastName = null;
        }

        contactCacheModel.firstName = getFirstName();

        String firstName = contactCacheModel.firstName;

        if ((firstName != null) && (firstName.length() == 0)) {
            contactCacheModel.firstName = null;
        }

        contactCacheModel.mail = getMail();

        String mail = contactCacheModel.mail;

        if ((mail != null) && (mail.length() == 0)) {
            contactCacheModel.mail = null;
        }

        contactCacheModel.phone = getPhone();

        String phone = contactCacheModel.phone;

        if ((phone != null) && (phone.length() == 0)) {
            contactCacheModel.phone = null;
        }

        return contactCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{personId=");
        sb.append(getPersonId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", lastName=");
        sb.append(getLastName());
        sb.append(", firstName=");
        sb.append(getFirstName());
        sb.append(", mail=");
        sb.append(getMail());
        sb.append(", phone=");
        sb.append(getPhone());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("org.rsc.liferay.contact.model.Contact");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>personId</column-name><column-value><![CDATA[");
        sb.append(getPersonId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>lastName</column-name><column-value><![CDATA[");
        sb.append(getLastName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>firstName</column-name><column-value><![CDATA[");
        sb.append(getFirstName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>mail</column-name><column-value><![CDATA[");
        sb.append(getMail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phone</column-name><column-value><![CDATA[");
        sb.append(getPhone());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
