package org.rsc.liferay.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;rsc_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.rsc.liferay.contact.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.rsc.liferay.contact.model.impl.ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contact
 * @see org.rsc.liferay.contact.model.impl.ContactImpl
 * @see org.rsc.liferay.contact.model.impl.ContactModelImpl
 * @generated
 */
public interface ContactModel extends BaseModel<Contact> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
     */

    /**
     * Returns the primary key of this contact.
     *
     * @return the primary key of this contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contact.
     *
     * @param primaryKey the primary key of this contact
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the person ID of this contact.
     *
     * @return the person ID of this contact
     */
    public long getPersonId();

    /**
     * Sets the person ID of this contact.
     *
     * @param personId the person ID of this contact
     */
    public void setPersonId(long personId);

    /**
     * Returns the company ID of this contact.
     *
     * @return the company ID of this contact
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this contact.
     *
     * @param companyId the company ID of this contact
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the last name of this contact.
     *
     * @return the last name of this contact
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this contact.
     *
     * @param lastName the last name of this contact
     */
    public void setLastName(String lastName);

    /**
     * Returns the first name of this contact.
     *
     * @return the first name of this contact
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this contact.
     *
     * @param firstName the first name of this contact
     */
    public void setFirstName(String firstName);

    /**
     * Returns the mail of this contact.
     *
     * @return the mail of this contact
     */
    @AutoEscape
    public String getMail();

    /**
     * Sets the mail of this contact.
     *
     * @param mail the mail of this contact
     */
    public void setMail(String mail);

    /**
     * Returns the phone of this contact.
     *
     * @return the phone of this contact
     */
    @AutoEscape
    public String getPhone();

    /**
     * Sets the phone of this contact.
     *
     * @param phone the phone of this contact
     */
    public void setPhone(String phone);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Contact contact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Contact> toCacheModel();

    @Override
    public Contact toEscapedModel();

    @Override
    public Contact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
